os: linux-ppc64le
sudo: false
dist: xenial
compiler:
  - gcc
language: c
before_install:
  - apt-get update -qq
  - apt-get install -y git gcc libssl-dev autoconf libgcrypt11-dev automake make flex bison bison+ pkg-config libtool libltdl-dev
script:
  - sh build.sh
  - ./configure
  - make CFLAGS="-Wno-error" && sudo make CFLAGS="-Wno-error" install && make CFLAGS="-Wno-error" check
